### ISSUE TITLE
[Bug Report] Crashes on app Split view

### ISSUE THREAD

**Issue by shuvashish76** [SamAmco/track-and-graph#124]
**Crash log**

```
FATAL EXCEPTION: main
Process: com.samco.trackandgraph, PID: 22404
java.lang.IllegalStateException: Fragment GroupFragment{3d50571} (ffcfad57-67cf-4b7f-9c69-f64cb640fd61)} has not been attached yet.
	at androidx.fragment.app.Fragment.getChildFragmentManager(Fragment.java:3)
	at com.samco.trackandgraph.group.GroupFragment.onMoveGraphStatClicked(GroupFragment.kt:6)
	at com.samco.trackandgraph.group.GroupFragment.access$onMoveGraphStatClicked(GroupFragment.kt:1)
	at com.samco.trackandgraph.group.GroupFragment$createGraphStatClickListener$4.invoke(GroupFragment.kt:2)
	at com.samco.trackandgraph.group.GroupFragment$createGraphStatClickListener$4.invoke(GroupFragment.kt:1)
	at com.samco.trackandgraph.group.GraphStatClickListener.onMoveGraphStat(GraphStatViewHolder.kt:1)
	at com.samco.trackandgraph.group.GraphStatViewHolder.onMenuItemClick(GraphStatViewHolder.kt:5)
	at android.widget.PopupMenu$1.onMenuItemSelected(PopupMenu.java:105)
	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:167)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:908)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:898)
	at com.android.internal.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1181)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3150)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

Same type crash as https://github.com/zhanghai/MaterialFiles/issues/574

**Comment by SamAmco** [comment]
Thanks for letting me know. A quick test shows this isn't happening on my device, if you could let me know your device / android version it might help me track down the issue.

**Comment by shuvashish76** [comment]
**Device Details**
App version: 2.0.3 (F-droid)
Android version: 8.1.0
Model: Lenovo Tab4 8plus (TB-8704X)

**Comment by YoshiRulz** [comment]
Also CNR on v2.3.2, LineageOS 17.1 (Android 10) on the OnePlus 6.
