### ISSUE TITLE
Crash while entering data

### ISSUE THREAD

**Issue by uli-on** [SamAmco/track-and-graph#221]
On my device T&G crashes reliably when I perform these steps:

- Tap the plus button of a tracker of type time/duration 
- tap any of the input fields for H/M/S
- Type any value
- Press the (soft-) keyboards Delete key
- Type any value: crash happens

Android 10
Fairphone 3
T&G v3.2.1 (f-droid or GH)
(Tested with 3 different soft-keyboards)

Stacktrace caught with the Scoop app:

```
FATAL EXCEPTION: main
Process: com.samco.trackandgraph, PID: 8545
java.lang.IllegalStateException: LayoutCoordinate operations are only valid when isAttached is true
	at o1.r0.i0(SourceFile:26)
	at c0.t1.a(SourceFile:93)
	at c0.l.e(SourceFile:64)
	at c0.p.d(SourceFile:119)
	at o1.u.x(SourceFile:41)
	at o1.h0.B(SourceFile:9)
	at s0.h$a.a(SourceFile:64)
	at s0.y$a.a(SourceFile:67)
	at s0.y.c(SourceFile:76)
	at o1.l1.a(SourceFile:13)
	at o1.f0$b.V0(SourceFile:143)
	at o1.f0$b.x(SourceFile:106)
	at e0.w$a.d(SourceFile:38)
	at o1.u.x(SourceFile:41)
	at c0.t2.I(SourceFile:76)
	at m1.u.o(SourceFile:13)
	at o1.a0.x(SourceFile:15)
	at c0.n0.o(SourceFile:35)
	at o1.c.o(SourceFile:15)
	at o1.a0.x(SourceFile:15)
	at z0.m0.o(SourceFile:6)
	at o1.a0.x(SourceFile:15)
	at w.c2.o(SourceFile:122)
	at o1.a0.x(SourceFile:15)
	at w.c2.o(SourceFile:122)
	at o1.a0.x(SourceFile:15)
	at o1.h0.B(SourceFile:9)
	at s0.h$a.a(SourceFile:64)
	at s0.y$a.a(SourceFile:67)
	at s0.y.c(SourceFile:76)
	at o1.l1.a(SourceFile:13)
	at o1.f0$b.V0(SourceFile:143)
	at o1.f0$b.x(SourceFile:106)
	at w.i.d(SourceFile:92)
	at o1.u.x(SourceFile:41)
	at w.c2.o(SourceFile:122)
	at o1.a0.x(SourceFile:15)
	at w.p1.o(SourceFile:38)
	at o1.a0.x(SourceFile:15)
	at m1.e0.b(SourceFile:17)
	at w.k1.o(Unknown Source:0)
	at o1.c.o(SourceFile:15)
	at o1.a0.x(SourceFile:15)
	at o1.h0.B(SourceFile:9)
	at s0.h$a.a(SourceFile:64)
	at s0.y$a.a(SourceFile:67)
	at s0.y.c(SourceFile:76)
	at o1.l1.a(SourceFile:13)
	at o1.f0$b.V0(SourceFile:143)
	at o1.l0.c(SourceFile:55)
	at o1.l0.k(SourceFile:32)
	at o1.l0.i(SourceFile:1)
	at o1.l0.i(SourceFile:41)
	at o1.l0.i(SourceFile:41)
	at o1.l0.i(SourceFile:41)
	at o1.l0.i(SourceFile:41)
	at o1.l0.i(SourceFile:41)
	at o1.l0.i(SourceFile:41)
	at o1.l0.i(SourceFile:41)
	at o1.l0.i(SourceFile:41)
	at o1.l0.h(SourceFile:30)
	at androidx.compose.ui.platform.AndroidComposeView.onMeasure(SourceFile:94)
	at android.view.View.measure(View.java:25090)
	at androidx.compose.ui.platform.a.g(SourceFile:64)
	at k2.p.g(SourceFile:87)
	at androidx.compose.ui.platform.a.onMeasure(SourceFile:4)
	at android.view.View.measure(View.java:25090)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25090)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25090)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:742)
	at android.view.View.measure(View.java:25090)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3081)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1855)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2144)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1743)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7772)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1041)
	at android.view.Choreographer.doCallbacks(Choreographer.java:864)
	at android.view.Choreographer.doFrame(Choreographer.java:798)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1026)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

**Comment by SamAmco** [comment]
Hi, sorry so this is actually an issue with the underlying compose library which i've reported to Google. In the meantime i fixed it by removing the hint text from v3.3.0 onwards. For some reason I forgot to update the latest version tag for f-droid to publish this fix. I've now updated this so hopefully v3.3.1 will be available on F-Droid soon. If it's blocking you it's possible to download the APK on git hub or get it on the play store in the meantime. Thanks for taking the time to report this issue.

**Comment by uli-on** [comment]
I know how to walk around that crash :) Thanks for all that you do here!
