### ISSUE TITLE
App crashes when click 'Notes'

### ISSUE THREAD

**Issue by ssssy1000** [SamAmco/track-and-graph#227]
## Environment
Device: pixel 5
Android Version: Android6.0
App Version: v3.5.1

## Description:
I change the app's theme to Dark, but the app change to whole black, while it recover, I click the button Notes and the app crashes.
I don't know if it's an accidental mistake, because I don't know how to reproduce it. 

## Screenshots:
<img width="200" alt="1688898650759" src="https://github.com/SamAmco/track-and-graph/assets/98003627/d1d06772-03f8-4b8a-9d93-a120d0254249">
<img width="199" alt="1688898639462" src="https://github.com/SamAmco/track-and-graph/assets/98003627/d12a7da0-020b-4ba0-8d7c-397c59d4f685">
<img width="198" alt="1688898676478" src="https://github.com/SamAmco/track-and-graph/assets/98003627/1411e5ec-0453-44fd-81bd-1e3b820cf05e">
<img width="198" alt="1688898726531" src="https://github.com/SamAmco/track-and-graph/assets/98003627/c9f9045a-b376-4a45-ac74-6a06609a7fd3">
<img width="197" alt="1688898742137" src="https://github.com/SamAmco/track-and-graph/assets/98003627/e24d897d-8caa-4e72-ac7d-4d90ab916c1b">
<img width="194" alt="1688898811174" src="https://github.com/SamAmco/track-and-graph/assets/98003627/7fe08968-5de9-4000-81be-2855e0810c2a">

## Crash log:
```
FATAL EXCEPTION: main
                                                              Process: com.samco.trackandgraph.debug, PID: 11905
                                                              java.util.ConcurrentModificationException
                                                               at java.util.WeakHashMap$HashIterator.next(WeakHashMap.java:165)
                                                               at androidx.core.view.ViewCompat$AccessibilityPaneVisibilityManager.onGlobalLayout(ViewCompat.java:4823)
                                                               at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:912)
                                                               at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1969)
                                                               at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                               at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                               at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                               at android.view.Choreographer$FrameDisplayEven
```

**Comment by SamAmco** [comment]
Woah. Interesting. I've never seen that one before. Thanks for reporting, I'll keep an eye out. I'm guessing you can't consistently reproduce this then?

**Comment by ssssy1000** [comment]
Yes, you guessed right, I didn't find a specific procedure to reproduce the bug

**Comment by SamAmco** [comment]
Must be gone, don't use the code in that stack trace anymore.
